# First ci with git Action

name: Android Pull Request to  Master CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
    - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #job1
  python-job: # python job
    - name: Run python script
      runs-on: ubuntu-latest

      steps:
      - name: setting up python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8

      - name: execute test-py script
        run: |
            python sysdemo.py "Manish Python test" lower
  #job 2
  unit-test:
   - name: Run Unit Tests
     runs-on: ubuntu-latest
  
     steps:
     - name: check out code
       uses: actions/checkout@v2

     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
          java-version: 1.8

     - name: Running Unit tests
       run: bash ./gradlew test --stacktrace

     - name: Running lint
       run: bash ./gradlew lintDebug

  #job3
  apk_build:  # all steps of this apk_build job will run on the same machine(here ubuntu-latest)
      - name: Generate APK
        runs-on: ubuntu-latest
        needs: unit_test  # only run after unit test succeed
     
        steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace
        - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
