# First ci with git Action

name: Android Pull Request to  Master CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
    - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: #  Jobs run in parallel by default. To run jobs sequentially, you can define dependencies on other jobs using the jobs.<job_id>.needs keyword.
  unit_test:  #   'unit_test' is a job id. all steps of this unit-test job will run on the same machine(here ubuntu-latest)
    name: Run Unit Tests
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Running Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Running lint
        run: bash ./gradlew lintDebug

  python-job: # python job
      name: Run python script
      runs-on: ubuntu-latest

      steps:
      - uses: actions/setup-python@v2
      - name: setting up python
      with:
        python-version: 3.8 #install the python needed
    - name: execute test-py script # run the run.py to get the latest data
      run: |
        python run.py "Manish Python test" lower

  apk_build:  # all steps of this apk_build job will run on the same machine(here ubuntu-latest)
      name: Generate APK
      runs-on: ubuntu-latest
      needs: unit_test  # only run after unit test succeed
     
      steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
